# Form implementation generated from reading ui file 'регистрация_родитель.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(290, 160, 211, 181))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.loginParent = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.loginParent.setText("")
        self.loginParent.setObjectName("loginParent")
        self.verticalLayout_2.addWidget(self.loginParent)
        self.passwordParent = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.passwordParent.setText("")
        self.passwordParent.setObjectName("passwordParent")
        self.verticalLayout_2.addWidget(self.passwordParent)
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_2.addWidget(self.lineEdit_3)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.registrParent = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.registrParent.setObjectName("registrParent")
        self.verticalLayout_3.addWidget(self.registrParent)
        self.vhodParent = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.vhodParent.setObjectName("vhodParent")
        self.verticalLayout_3.addWidget(self.vhodParent)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.loginParent.setPlaceholderText(_translate("MainWindow", "логин"))
        self.passwordParent.setPlaceholderText(_translate("MainWindow", "пароль"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "подтвердите пароль"))
        self.registrParent.setText(_translate("MainWindow", "регистрация"))
        self.vhodParent.setText(_translate("MainWindow", "вход"))
